### ISSUE TITLE
Rule disable option

### ISSUE THREAD

**Issue by skyferix** [ergebnis/phpstan-rules#518]
Type: feature

Add rules disable functionality. 
From config perpective it could look something like this:

```
ergebnis:
              NoExtendsRule:
                       enable: false

              // then other options to rules could look like this
              FinalRule:
                       allowAbstractClasses: false
                       classesNotRequiredToBeAbstractOrFinal:
			       - Foo\Bar\NeitherAbstractNorFinal
```
                       
This way there is rule options indepencdence
